### ISSUE TITLE
Solid.Translate on z axis

### ISSUE THREAD

**Issue by talanc** [arakis/Net3dBool#3]
https://github.com/arakis/Net3dBool/blob/39354914eba2f9d34aedd2a16a6528d50e19beec/src/Net3dBool/Solid.cs#L157

You cannot move a Solid object on the z axis.

Happy to do the work, let me know if you want a PR for this.

        /**
        * Applies a translation into a solid
        * 
        * @param dx translation on the x axis
        * @param dy translation on the y axis
        * @param dz translation on the z axis
        */
        public void Translate(double dx, double dy, double dz)
        {
            if (dx != 0 || dy != 0 || dz != 0)
            {
                for (int i = 0; i < Vertices.Length; i++)
                {
                    Vertices[i].X += dx;
                    Vertices[i].Y += dy;
                    Vertices[i].Z += dz;
                }

                DefineGeometry();
            }
        }

**Comment by arakis** [comment]
Did you testet that well?
If yes, i place it in the repo.

Damm, we do not have any automated tests :-/

**Comment by talanc** [comment]
Don't worry -- I just noticed "Zoom(double dz)".
